muammar/mkchromecast

mkchromecast/cast.py

When I tried to run mkchromecast on my Arch Linux, I got an `AttributeError: module 'pychromecast' has no attribute 'get_chromecasts_as_dict'`. It seems the current version of pychromecast does not have this function anymore.
I added support for the current version of pychromecast while making the code backwards compatible.
BTW, thanks for this great project!

Support newer versions of pychromecast

---

mkchromecast/cast.py

http://stackoverflow.com/questions/6470428/catch-multiple-exceptions-in-one-line-except-block
Python 3 needs parenthesise to work correctly when catching multiple exceptions

Making ping code python 3 compatible

---

mkchromecast/tray_threading.py

availablecc() was not called and so availablecc was being interpreted as the method, not the property.
```
Traceback (most recent call last):
File "/work/Dev/mkchromecast/mkchromecast/tray_threading.py", line 48, in _search_cast_
if len(self.cc.availablecc) == 0 and tray == True:
TypeError: object of type 'instancemethod' has no len()
Aborted
```

Fixed issue with running start_tray.py

---

README.md
changelog.md
mkchromecast/audio.py
mkchromecast/cast.py
mkchromecast/preferences.py
mkchromecast/pulseaudio.py
mkchromecast/systray.py
mkchromecast/tray_threading.py

This is an attempt to add Sonos support.
Adding support for sonos is very easy. Just install the `soco` module by:
```
pip install soco
```
That's it. Note that at this stage, most of the options may still be broken. Systray is partially working, and only `mp3` codec is supported. If you find a problem, please do not hesitate to report it. 
If  you have both chromecasts and sonos speakers, use the `-s` flag to choose from the list :).

Sonos support

---

mkchromecast.py

The current signal handling is hard to work with if you want to fork the process into the background, as input() will get an EOF error. Reworked the current handling with the `signal` module.
A little unsure how this will work on OSX and Windows as i don't have anything to test with.
Signed-off-by: Morten Linderud <morten@linderud.pw>

Fixed propper signal handling instead of input

---

mkchromecast/colors.py

`unicode()`was dropped from Python 3 because all strs are Unicode by default.

define unicode() in Python 3

---

mkchromecast.py

Was unable to play YouTube videos on Linux due to a variable scoping oversight.

Added a missing self in audio_linux

---

mkchromecast.py
mkchromecast/systray.py
mkchromecast/video.py
requirements.txt

I've done three changes to adapt mkchromecast to my needs:
- Modified how pyqt is used to accomodate pyqt 5.5, which is what comes in Ubuntu 17.04 LTS
- Removed the -max_muxing_queue_size ffmpeg flag because it's not supported in ffmpeg 2.8.11 (the one I have in Ubuntu 17.04 LTS)
- Most importantly, added initial hacky support for screencasting with audio (pulseaudio) in Linux
Regarding this last point of audio&video, I remark it's been done in a hacky way because I'm asuming it's always done with pulseaudio and Linux. But just doing what @muammar suggested in https://github.com/muammar/mkchromecast/issues/104#issuecomment-357790035 didn't work for me because I wanted a monitor sink to be created. 
Anyway, this is just my way of sharing something that works, I don't expect this to be …

adding audio to screencasting and ubuntu LTS support

---

.gitignore
bin/mkchromecast
mkchromecast.1
setup.py

This PR is the underpinnings in master for #170 and #172. Basically, it makes mkchromecast to a complete pypi package on the Linux side, installable using pip3 and related tools. This simplifies things for both packagers and users on platforms without a native package.  
If/when this PR is accepted,  #170 and #172 need to be rebased to the new master before being merged, but that is a later issue. Basically, this PR is first part of #172. 
The PR contains untested changes with respect to MacOS builds. So, please verify this before merging!

master: Add linux support to setup.py

---

.gitignore
mkchromecast/audio.py
mkchromecast/cast.py
mkchromecast/utils.py
mkchromecast/video.py

Originally thought to fix #199, but now I don't believe it is the proper fix.
Still, it might be worth merging in the name of code cleanup?
The Flask app now listens on the externally available/resolved IP address of the host instead of `0.0.0.0`. This is the same address as the `Local IP`, either set by `--host` on command line or auto-detected.

Bind Flask to visible IP address

---

mkchromecast/video.py

Previously, the error message would be about Node missing
from the system because Popen fails. We therefore check
for a missing `input_file` before trying Popen.

Better error message when Node input file is omitted

---

mkchromecast/__init__.py
mkchromecast/video.py

Sorry for the pull request spam.  I prefer using h264_nvenc for encoding because of performance on my machine.  This patch adds a --vcodec option defaulting to libx264 which changes the vcodec used by ffmpeg when casting the screen.  I also had to remove the preset flag from the ffmpeg command when this is set to h264_nvenc.  I don't have an AMD card to test their hardware encoding, so there may be compatibility issues there that I was unable to test for.  Hopefully someone will open an issue if they encounter any.

add support for custom video codecs in ffmpeg

---

mkchromecast/video.py

mkchromecast --control --video -i Test.mp4 --seek 05:00

Move 'if seek' to parent block otherwise --seek option fails using example: 

---

mkchromecast/__init__.py

Previously, this did not work, due to a space in the file name, regardless of quoting or nested quotes:
mkchromecast --video --command "ffmpeg -re -i 'test file.mp4' -map_chapters -1 -vcodec libx264 -preset ultrafast -tune zerolatency -maxrate 10000k -bufsize 20000k -pix_fmt yuv420p -g 60 -f mp4 -max_muxing_queue_size 9999 -movflags         frag_keyframe+empty_moov pipe:1"

Fixing filenames with spaces

---

mkchromecast/video.py

ffmpeg now generates a temporary file with subtitles adjusted to the '--seek' option time.

Fixed the issue with subtitles not syncing when used along with the --seek option

---

mkchromecast/pulseaudio.py

The current implementation of `remove_sink()` removes all `module-null-sink`s, whether or not they were installed by Mkchromecast, which can cause problems if null sinks are being used for other purposes. This PR changes the behavior to remember the id of the sink created and removes just that one.

Avoid removing unrelated PulseAudio null sinks.

---

mkchromecast/pulseaudio.py

Avoid the extra `pacmd` call by setting the sink description in the initial `pactl` command.

Set sink description in load-module command.

---

mkchromecast/__init__.py
mkchromecast/cast.py
mkchromecast/pulseaudio.py
mkchromecast/systray.py

My Linux distribution is now providing `pychromecast 7.1.1` and higher. So I made some changes to make `mkchromecast` works with my setting.
1. I only have one Google Home Mini, so I didn't look into video and YouTube streaming. Only checked the audio casting.
2. I don't use the systray. So not sure if the systray works.
3. Tested with both `pychromecast 7.2.0` and `7.1.0`. Didn't go back further.
4. Tested with Python 3.8.
Because my use case is very limited, these are small changes. But still, hope this can help some users.
1. improving `--reset` by adding `get_sink_list` and modifying `remove_sink`:
If `mkchromecast` crashed due to some reasons, sometimes the sinks it created were still there. Running with `--reset` would not kill those residual sinks because …

Partially make pychromecast v7.2.0 compatible

---

bin/mkchromecast

On linux, it is common to symlink from a location already within the path (e..g /usr/bin) to the actual binary. This breaks mkchromecast's import scheme. By wrapping __file__ in a real path call, we can make the system work with symlinks like this without changing anything else (e.g. it works as expected all other times)

Support symlinking to the main binary

---

Makefile

@muammar This PR contains some minor improvements in the Makefile plus adds a target that builds the mkchromecast without starting in tray mode. The tray mode seems to have some problems casting audio sufficiently on linux currently plus is being marked as beta anyway. The last working package in debian (Version: 0.3.8.1-1) didn't start in tray mode. Please see as well my other PR for the debian branch.

[master] Makefile changes for debian

---

MANIFEST.in

When run outside of a Git checkout, setuptools somehow fails to find the `mkchromecast.getch` subpackage and install it, resulting in broken functionality.
I’m not sure why exactly this is necessary. I found out about this accidentally when a user complained the control functionality was broken in the latest Debian package. I checked it locally and it worked, and then I found out the packages built at buildds were missing these files. I rebuilt locally again and everything went fine. I the ran `apt source` elsewhere and built there — and the files were missing.

Explicitly add getch subpackage to the manifest

---

mkchromecast/__init__.py

Fixes deprecation warning by using raw string 
```
find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}   
./mkchromecast/__init__.py:542: DeprecationWarning: invalid escape sequence \?
help="""
```

Fix deprecation warnings due to invalid escape sequences.

---

mkchromecast/pulseaudio.py

The reset subcommand was failing to clean up left over sinks, as the
output of `pactl list sinks` is considerably different to the output of
`pacmd list sinks`.

Fix regex used to parse sink list

---

test.py

In particular, this is important to have mypy highlight type errors from parts
of the codebase that haven't yet been annotated with types, but that might
already be misusing types that have been annotated.

Tells mypy to check untyped defs.

---

mkchromecast/__init__.py
mkchromecast/_arg_parsing.py
test.py
tests/__init__.py
tests/test_instantiate.py

This was necessary to ensure that the new Mkchromecast class could be
instantiated.  But also, it paves the way for creating an actual suite of unit
tests as the broader refactor continues and more functionality is encapsulated
as classes.

Creates the beginnings of a unit test suite, and runs those unit tests when `test.py` is run

---

README.md
bin/mkchromecast
mkchromecast/__init__.py
mkchromecast/_arg_parsing.py
mkchromecast/audio.py
mkchromecast/cast.py
mkchromecast/constants.py
mkchromecast/preferences.py
tests/test_constants.py

Also centralizes backend listing in constants.py, and simplifies code that shouldn't have an explicit dependency on backend names in the first place.
Note that this is untested with the node backend, which uses a lot of separate codepaths, so it wouldn't be surprising if this introduces unnoticed issues for node-based playback.

Drops support for avconv, which is defunct.

---

mkchromecast/__init__.py
mkchromecast/_arg_parsing.py
mkchromecast/audio.py
mkchromecast/config.py
mkchromecast/constants.py
mkchromecast/messages.py
mkchromecast/node.py
mkchromecast/pipeline_builder.py
mkchromecast/stream_infra.py
mkchromecast/utils.py
tests/test_pipeline_builder.py
tests/test_utils.py

This makes more progress on #434.

Uses bitrate as int throughout mkchromecast, and ensures that it is always non-None.

---

mkchromecast/cast.py

Confusingly, the mtype access bug also caused sonos cleanup to be triggered, which is incorrect.
Fixes #445

Works around mtype access bug, and makes chromecast cleanup and sonos cleanup independent

---

bin/mkchromecast
mkchromecast/__init__.py
mkchromecast/_arg_parsing.py
mkchromecast/stream_infra.py
mkchromecast/utils.py
mkchromecast/video.py
start_tray.py

This fixes the single-time arg-parsing behavior as specified in #425, and is an important step towards continuing to simplify cascading logic as covered by #434

Starts to adjust codepaths to simplify how mkchromecast operates, and to more clearly distinguish between distinct operating modes.

---

bin/mkchromecast
mkchromecast/__init__.py
mkchromecast/_arg_parsing.py
mkchromecast/audio.py
mkchromecast/cast.py
mkchromecast/constants.py
mkchromecast/node.py
mkchromecast/pipeline_builder.py
mkchromecast/preferences.py
mkchromecast/tray_threading.py
mkchromecast/utils.py
mkchromecast/video.py
tests/test_instantiate.py
tests/test_pipeline_builder.py

The goal is to reduce the number of places that need to test for different (and sometimes conflicting) operation mode flags, and to simplify and streamline the codepaths for each.

Creates a new "Operation Mode" enum that establishes the unique purpose of this mkchromecast invocation.

---

mkchromecast/_arg_parsing.py
mkchromecast/constants.py
mkchromecast/pipeline_builder.py
mkchromecast/preferences.py
mkchromecast/stream_infra.py

This is mainly just cleanup, since the actual gstreamer support was in a non-functional and commented-out state and was mostly dropped in the pipeline_builder refactor.

Drops remaining mentions of gstreamer.

---

bin/mkchromecast
mkchromecast/cast.py
mkchromecast/messages.py
mkchromecast/systray.py
mkchromecast/tray_threading.py

- Resolves ambiguity of `available_devices` as being a method or a list
- Creates an AvailableDevice dataclass to simplify data access
- Moves `print_available_devices` helper to cast.py
- Creates a currently-non-functional backup and drops Sonos support from main Casting class
- Drops long-deprecated reboot support
Also, this avoids using `available_devices` as a global variable, which makes progress on #425

Major refactor and simplification of cast.py

---

mkchromecast/cast.py

Resolves this error when attempting to run `bin/mkchromecast`.
```
Traceback (most recent call last):
File "/home/<username>/mkchromecast/bin/mkchromecast", line 288, in <module>
CastProcess(mkcc).run()
File "/home/<username>/mkchromecast/bin/mkchromecast", line 68, in run
self.start_audiocast()
File "/home/<username>/mkchromecast/bin/mkchromecast", line 97, in start_audiocast
self.cc.initialize_cast()
File "/home/<username>/mkchromecast/bin/../mkchromecast/cast.py", line 114, in initialize_cast
print_available_devices(self.available_devices)
File "/home/<username>/mkchromecast/bin/../mkchromecast/cast.py", line 62, in print_available_devices
print(device)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 13: ordinal not in range(256)
Killed
```
For context, …

Encode available device names to UTF-8

---

mkchromecast/__init__.py
tests/test_instantiate.py

**Scope**: There was an issue that the MP3 Codec was not assigned if it was assigned when using the Node Backend. If no codec, or any other codec was set, this would be set back to the MP3 codec. 
Related Issue: https://github.com/muammar/mkchromecast/issues/468 
**Work done**:
* The first commit covers a unit-test to replicate this issue. The error was reproducible by setting the backend to `Node` and the Codec to `MP3` as specified in the issue. 
* The second commit changes the indentation, assigning the MP3 codec in all cases of the `Node` backend. The print out is still specific to any other codec, explaining that it has been reset to MP3, as the node backend only supports MP3.

Fixing missing assignment of MP3 Codec when specified, in conjucture with the Node backend
